# Generated by Django 4.2.3 on 2024-01-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField()),
                ('editor', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='library_admin.author')),
                ('category', models.ManyToManyField(to='library_admin.category')),
            ],
        ),
    ]
