# Generated by Django 4.2.3 on 2024-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0002_alter_book_author_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
