# Generated by Django 4.2.3 on 2024-01-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0003_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='book', to='library_admin.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='book', to='library_admin.category'),
        ),
    ]
