# Generated by Django 4.2.3 on 2024-01-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_admin", "0004_alter_book_author_alter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
